version: '2'

services:
  scrumkin:
    build: .
    volumes:
      - ".:/go/src/scrumkin"
    environment:
      DATABASE_DSN: root:scrumkinpass@tcp(mysqldb:3306)/scrumkin
    links:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: scrumkinpass
      MYSQL_DATABASE: scrumkin
